### ISSUE TITLE
[BUG] End Turn button randomly disappears for session

### ISSUE THREAD

**Issue by GaistH** [dmrickey/token-action-hud-pf1#12]
**Describe the bug**
Difficult to replicate during downtime troubleshooting, but this seems to plague us frequently during live sessions in PF1E -- the End Turn button will randomly stop showing up for various actors (NPCs or PCs, doesn't particularly matter) requiring going to the combat tab to resume advancing turns.  It just outright vanishes from the available buttons, even though others like e.g. Remove Combatant remain.

**To Reproduce**
Get several rounds into combat with 10+ actors and odds are one of them loses the End Turn option.

**Expected behavior**
End Turn to remain present throughout combat encounters for all actors involved in the combat.

**Screenshots**

**What version of TAH pf1/core are you using?**
pf1: v1.3.7
core: v1.4.16

**Comment by dmrickey** [comment]
This should be fixed now. Please re-open if you see this happening again.
