### ISSUE TITLE
Error requiring version of Core, yet newer version is installed

### ISSUE THREAD

**Issue by ckdragons** [dmrickey/token-action-hud-pf1#2]
![image](https://user-images.githubusercontent.com/84493092/230517583-383baf91-1e63-49ad-b0f3-a784451d0658.png)

![image](https://user-images.githubusercontent.com/84493092/230517602-7d586826-3ffd-4120-8342-6116bb38e7f4.png)

HUD does not work with these options enabled.

**Comment by dmrickey** [comment]
The "error" is correct. Whenever the Core module is updated it breaks (or _can break_, as in this case) any system modules. The error doesn't say "requires _at least_ 1.2", it's specifically that 1.2 _and only 1.2_ works. As long as Core isn't updated, then the pf1 module continues to work. So when Core is updated, any system-mod needs to be updated to accommodate the breaking changes from Core.

An update has already been pushed out though, and is now compatible with 1.3. However 1.4 will be coming out soon, and the same thing will apply then.

**Comment by ckdragons** [comment]
Thank you. So if i understand correctly, I should update both modules ONLY when Core is updated?

**Comment by dmrickey** [comment]
Core version numbers are 1.x.y, any `y` update should be compatible. Any `x` update requires the system module to update to be compatible. I would say to only update a core `x` version if the system says it needs it
