### ISSUE TITLE
Performance Issues with Statblock Library

### ISSUE THREAD

**Issue by Tarbarian** [dmrickey/token-action-hud-pf1#6]
Having the two modules of [Token Action Hud Pathfinder 1e](https://github.com/dmrickey/token-action-hud-pf1/) and [Pathfinder 1e Statblock](https://github.com/baileymh/statblock-library) causes significant performance issues.
![image](https://user-images.githubusercontent.com/76751079/235312449-9d8488c8-c65f-4ed0-b035-c34e30b2353f.png)

Movement with both modules enabled:
![WithHud](https://user-images.githubusercontent.com/76751079/235312461-e1aecf9d-fe96-4345-9402-28f80b2be371.gif)

Movement with either of the modules disabled:
![WithoutHud](https://user-images.githubusercontent.com/76751079/235312460-5497344a-0918-4499-b516-821a5b7e6d01.gif)

No idea why, these modules just don't seem to like each other.

**Comment by Tarbarian** [comment]
Cross post for the other module: [link](https://github.com/baileymh/statblock-library/issues/21)

**Comment by dmrickey** [comment]
Can you try this again and see if you notice any difference? There was a bug in Core where it was attempting to update whenever a token moved.

**Comment by Tarbarian** [comment]
Looks like that was it! No signs of the same reduced performance now. Thanks!
